name: flutter_player
description: A Flutter-based external player for FnTV Client.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  media_kit_libs_windows_video: ^1.0.8
  window_manager: ^0.3.7
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.6.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  lottie: ^3.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
